using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nop.Plugin.Misc.CycleFlow
{
    public static class CycleFlowPluginLocalizationResources
    {
        public static IDictionary<string, string> PluginResources(string LangCode)
        {
            switch (LangCode.ToLower())
            {
                case "en":
                    return PluginEnglishResources();
                case "ar":
                    return PluginArabicResources();

                default: return PluginEnglishResources();
            }
        }
        private static IDictionary<string, string> PluginEnglishResources()
        {
            return new Dictionary<string, string>
            {
                #region English
                ["Nop.Plugin.Misc.CycleFlow.CycleFlow"] = "CycleFlow",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Fields.Name"] = "Name",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Fields.Description"] = "Description",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Fields.IsActive"] = "Is Active",
                ["Nop.Plugin.Misc.CycleFlow.OrderStatus.Name.Unique"] = "Name Must Be Unique",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Fields.SearchName"] = "Search Name",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Title"] = "Order Status",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.EditOrderStatusDetails"] = "Edit Order Status Details",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.BackToList"] = "Back To List",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.AddNew"] = "Add New Order Status",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Info"] = "Order Status Info",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Notification.Deleted"] = "Order Status Deleted",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Notification.Updated"] = "Order Status Updated",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Notification.Added"] = "Order Status Added",
                ["Nop.Plugin.Misc.CycleFlow.OrderStatus"] = "Order Status",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Fields.Name"] = "Name",
                ["Nop.Plugin.Misc.CycleFlow.ImageType.Name.Unique"] = "Name Must Be Unique",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Fields.SearchName"] = "Search Name",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Title"] = "Image Type",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.EditImageTypeDetails"] = "Edit Image Type Details",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.BackToList"] = "Back To List",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.AddNew"] = "Add New Image Type",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Info"] = "Image Type Info",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Notification.Deleted"] = "Image Type Deleted",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Notification.Updated"] = "Image Type Updated",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Notification.Added"] = "Image Type Added",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Manage"] = "Manage Cycle Flow",
                ["Nop.Plugin.Misc.CycleFlow.ImageType"] = "Image Type",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Title"] = "Cycle Flow Setting",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CurrentOrderStatusName"] = "Current Order Status Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.StoreName"] = "Store Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.PosUserName"] = "Pos User Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NextOrderStatusName"] = "Next Order Status Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CurrentOrderStatusId"] = "Current Order Status Id",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.StoreId"] = "Search Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NopWarehouseId"] = "Store Id",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.PosUserId"] = "Pos User Id",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NextOrderStatusId"] = "Next Order Status Id",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NopWarehouseName"] = "Warehouse Name",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting"] = "Cycle Flow Setting",
                ["Admin.Plugin.Misc.CycleFlow.Common.Select"] = "Select",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CheckResult"] = "CheckResult",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.ClientSmsTemplateId"] = "Client Sms Template",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.UserSmsTemplateId"] = "User Sms Template",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.Store.Required"] = "Store is required",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.Customer.Required"] = "Customer is required",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.PosUser.Required"] = "POS User is required",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.CurrentOrderStatusId.Found"] = "Current Order Status already exists in the sorting list",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.NextOrderStatusId.Found"] = "Next Order Status already exists in the sorting list",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.IsFirstStep.Found"] = "The first step cannot be enabled for more than one status",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.IsLastStep.Found"] = "The last step cannot be enabled for more than one status",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.ClientSmsTemplateId.MustSelect"] = "Client SMS Template must be selected",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.UserSmsTemplateId.MustSelect"] = "User SMS Template must be selected",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.IsEnableSendToUser.MustTrue"] = "IsEnableSendToUser must be true if User Sms Template Id is set",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.IsEnableSendToClient.MustTrue"] = "IsEnableSendToClient must be true if Client Sms Template Id is set",
                ["Admin.Plugin.Misc.CycleFlow.CheckPosOrderStatus.Title"] = "Check POS Order Status",
                ["Admin.Plugin.Misc.CycleFlow.CheckPosOrderStatusModel.Fields.PosUserName"] = "POS User Name",
                ["Admin.Plugin.Misc.CycleFlow.ResultOfCheck"] = "Result Of Check",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Title"] = "Cycle Flow Setting",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.StoreName"] = "Store Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.PosUserName"] = "POS User Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CurrentOrderStatusName"] = "Current Order Status Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NextOrderStatusName"] = "Next Order Status Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.EditOrderStatusDetails"] = "Edit Order Status Details",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.EditOrderStatusDetails"] = "Edit Order Status Details",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.BackToList"] = "Back to List",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.AddNew"] = "Add New",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.BackToList"] = "Back to List",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.EditOrderStatusDetails"] = "Edit Order Status Details",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.BackToList"] = "Back to List",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Info"] = "Info",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Send"] = "Send",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.SearchPosUser"] = "SearchPosUser",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CurrentOrderStatus"] = "Current Order Status",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.Store"] = "Store",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.Customer"] = "Customer",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.PosUser"] = "POS User",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NextOrderStatus"] = "Next Order Status",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.SelectedImageType"] = "Selected Image Type",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.IsFirstStep"] = "Is First Step",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.IsLastStep"] = "Is Last Step",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.ClientSmsTemplate"] = "Client Sms Template",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.IsEnableSendToClient"] = "Is Enable Send To Client",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.UserSmsTemplate"] = "User Sms Template",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.IsEnableSendToUser"] = "Is Enable Send To User",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.SearchName"] = "Search by Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.SearchPosUser"] = "Search POS User",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.SearchStore"] = "Search Store",
                ["Nop.Plugin.Misc.CycleFlow.CheckPosOrderStatus"] = "Check Order Status ٍSorting Setting",
                ["Admin.Plugin.CycleFlow.CycleFlowSetting.Fields.SearchStore"] = "Search Store",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CurrentOrderStatusName"] = "Current Order Status Name",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.PosUserName"] = "Pos User Name",
                ["Admin.Plugin.Misc.CycleFlow.Deportation.Check"] = "Sequencing error for {0} - {1} The sequence is incomplete For Charting {2} and Editing {3}",

                #endregion
            };
        }

        private static IDictionary<string, string> PluginArabicResources()
        {
            return new Dictionary<string, string>
            {
                #region Arabic
                ["Nop.Plugin.Misc.CycleFlow.CycleFlow"] = "الدوره المستنديه",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Fields.Name"] = "اسم",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Fields.Description"] = "الوصف",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Fields.IsActive"] = "نشط",
                ["Nop.Plugin.Misc.CycleFlow.OrderStatus.Name.Unique"] = "يجب أن يكون الاسم فريدًا",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Fields.SearchName"] = "اسم البحث",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Title"] = "حالة الطلب",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.EditOrderStatusDetails"] = "تعديل تفاصيل حالة الطلب",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.BackToList"] = "العودة إلى القائمة",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.AddNew"] = "إضافة حالة طلب جديدة",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Info"] = "معلومات حالة الطلب",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Notification.Deleted"] = "تم حذف حالة الطلب",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Notification.Updated"] = "تم تحديث حالة الطلب",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.Notification.Added"] = "تم إضافة حالة الطلب",
                ["Nop.Plugin.Misc.CycleFlow.OrderStatus"] = "حالة الطلب",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Fields.Name"] = "اسم",
                ["Nop.Plugin.Misc.CycleFlow.ImageType.Name.Unique"] = "يجب أن يكون الاسم فريدًا",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Fields.SearchName"] = "اسم البحث",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Title"] = "نوع الصورة",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.EditImageTypeDetails"] = "تعديل تفاصيل نوع الصورة",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.BackToList"] = "العودة إلى القائمة",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.AddNew"] = "إضافة نوع صورة جديدة",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Info"] = "معلومات نوع الصورة",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Notification.Deleted"] = "تم حذف نوع الصورة",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Notification.Updated"] = "تم تحديث نوع الصورة",
                ["Admin.Plugin.Misc.CycleFlow.ImageType.Notification.Added"] = "تم إضافة نوع الصورة",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Manage"] = "إدارة الدورة المستندية",
                ["Nop.Plugin.Misc.CycleFlow.ImageType"] = "نوع الصورة",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Title"] = "إعدادات الدورة المستندية ",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CurrentOrderStatusName"] = "اسم حالة الطلب الحالية",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.StoreName"] = "اسم المتجر",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.PosUserName"] = "اسم مستخدم الـ POS",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NextOrderStatusName"] = "اسم حالة الطلب التالية",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CurrentOrderStatusId"] = "معرف حالة الطلب الحالية",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.StoreId"] = "اسم البحث",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NopWarehouseId"] = "معرف المتجر",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.PosUserId"] = "معرف مستخدم الـ POS",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NextOrderStatusId"] = "معرف حالة الطلب التالية",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NopWarehouseName"] = "اسم المستودع",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting"] = "إعدادات الدورة المستندية ",
                ["Admin.Plugin.Misc.CycleFlow.Common.Select"] = "اختيار",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CheckResult"] = "نتيجة الفحص",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.ClientSmsTemplateId"] = "قالب الرسالة النصية للعميل",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.UserSmsTemplateId"] = "قالب الرسالة النصية للمستخدم",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.Store.Required"] = "المتجر مطلوب",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.Customer.Required"] = "العميل مطلوب",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.PosUser.Required"] = "مستخدم الـ POS مطلوب",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.CurrentOrderStatusId.Found"] = "حالة الطلب الحالية موجودة بالفعل في قائمة التصفية",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.NextOrderStatusId.Found"] = "حالة الطلب التالية موجودة بالفعل في قائمة التصفية",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.IsFirstStep.Found"] = "لا يمكن تمكين الخطوة الأولى لأكثر من حالة واحدة",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.IsLastStep.Found"] = "لا يمكن تمكين الخطوة الأخيرة لأكثر من حالة واحدة",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.ClientSmsTemplateId.MustSelect"] = "يجب تحديد قالب الرسالة النصية للعميل",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.UserSmsTemplateId.MustSelect"] = "يجب تحديد قالب الرسالة النصية للمستخدم",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.IsEnableSendToUser.MustTrue"] = "يجب أن يكون IsEnableSendToUser صحيحًا إذا تم تعيين قالب الرسالة النصية للمستخدم",
                ["Nop.Plugin.Misc.CycleFlow.CycleFlowSetting.IsEnableSendToClient.MustTrue"] = "يجب أن يكون IsEnableSendToClient صحيحًا إذا تم تعيين قالب الرسالة النصية للعميل",
                ["Admin.Plugin.Misc.CycleFlow.CheckPosOrderStatus.Title"] = "تحقق من حالة الطلب في الـ POS",
                ["Admin.Plugin.Misc.CycleFlow.CheckPosOrderStatusModel.Fields.PosUserName"] = "اسم مستخدم الـ POS",
                ["Admin.Plugin.Misc.CycleFlow.ResultOfCheck"] = "نتيجة الفحص",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Title"] = "إعدادات الدورة المستندية ",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.StoreName"] = "اسم المتجر",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.PosUserName"] = "اسم مستخدم الـ POS",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CurrentOrderStatusName"] = "اسم حالة الطلب الحالية",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NextOrderStatusName"] = "اسم حالة الطلب التالية",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.EditOrderStatusDetails"] = "تعديل تفاصيل حالة الطلب",
                ["Admin.Plugin.Misc.CycleFlow.OrderStatus.EditOrderStatusDetails"] = "تعديل تفاصيل حالة الطلب",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.BackToList"] = "العودة إلى القائمة",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.AddNew"] = "إضافة جديدة",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.BackToList"] = "العودة إلى القائمة",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.EditOrderStatusDetails"] = "تعديل تفاصيل حالة الطلب",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.BackToList"] = "العودة إلى القائمة",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Info"] = "معلومات",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Send"] = "إرسال",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CurrentOrderStatus"] = "حالة الطلب الحالية",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.Store"] = "المتجر",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.Customer"] = "العميل",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.PosUser"] = "مستخدم نقاط البيع",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.NextOrderStatus"] = "حالة الطلب التالية",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.SelectedImageType"] = "نوع الصورة المحدد",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.IsFirstStep"] = "هل هذه هي الخطوة الأولى",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.IsLastStep"] = "هل هذه هي الخطوة الأخيرة",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.ClientSmsTemplate"] = "قالب رسالة العميل",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.IsEnableSendToClient"] = "تمكين إرسال إلى العميل",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.UserSmsTemplate"] = "قالب رسالة المستخدم",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.IsEnableSendToUser"] = "تمكين إرسال إلى المستخدم",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.SearchName"] = "البحث باسم الحاله",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.SearchPosUser"] = "بحث عن مستخدم نقاط البيع",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.SearchStore"] = "بحث عن المتجر",
                ["Nop.Plugin.Misc.CycleFlow.CheckPosOrderStatus"] = "تحقق من اعدادات الدوره المستنديه",
                ["Admin.Plugin.CycleFlow.CycleFlowSetting.Fields.SearchStore"] = "بحث عن المتجر",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.CurrentOrderStatusName"] = "حالة الطلب الحالية",
                ["Admin.Plugin.Misc.CycleFlow.CycleFlowSetting.Fields.PosUserName"] = "اسم نقطة البيع",
                ["Admin.Plugin.Misc.CycleFlow.Deportation.Check"] = "خطأ في التسلسل لـ {0} - {1}. التسلسل غير مكتمل لرسم المخططات {2} وتحرير {3}.",
                #endregion
            };
        }
    }
}
